import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { MedicalData, PredictionResult } from './types';

export const generatePDFReport = (data: MedicalData, result: PredictionResult) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(11, 92, 146); // Brand color: #0b5c92
  doc.text('Diabetes Risk Assessment Report', 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 14, 28);
  
  // Patient Medical Data Section
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Patient Medical Parameters', 14, 40);

  const medicalDataRows = Object.entries(data).map(([key, value]) => {
    // Format keys (e.g., bloodPressure -> Blood Pressure)
    const formattedKey = key
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, (str) => str.toUpperCase());
    return [formattedKey, value.toString()];
  });

  autoTable(doc, {
    startY: 45,
    head: [['Parameter', 'Value']],
    body: medicalDataRows,
    theme: 'striped',
    headStyles: { fillColor: [11, 92, 146] }
  });

  // AI Prediction Results Section
  const finalY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? 45;
  
  doc.setFontSize(14);
  doc.text('AI Prediction Results', 14, finalY + 15);
  
  // Risk Level
  doc.setFontSize(12);
  let riskColor: [number, number, number] = [0, 0, 0];
  if (result.riskLevel === 'Low') riskColor = [30, 189, 149]; // #1ebd95
  else if (result.riskLevel === 'Medium') riskColor = [245, 158, 11]; // amber-500
  else if (result.riskLevel === 'High') riskColor = [239, 68, 68]; // red-500

  doc.setTextColor(0, 0, 0);
  doc.text('Risk Level: ', 14, finalY + 25);
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.text(result.riskLevel, 40, finalY + 25);

  // Probability
  doc.setTextColor(0, 0, 0);
  doc.text('Probability: ', 14, finalY + 33);
  doc.text(`${result.probability}%`, 40, finalY + 33);

  // Insights
  doc.text('Key Insights:', 14, finalY + 45);
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  
  let insightY = finalY + 52;
  result.insights.forEach((insight) => {
    // Split long text
    const lines = doc.splitTextToSize(`• ${insight}`, 180);
    doc.text(lines, 14, insightY);
    insightY += lines.length * 6;
  });

  // Disclaimer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  const disclaimerText = 'Disclaimer: This report is generated by an AI model for informational purposes only and does not constitute professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider regarding any health concerns.';
  const disclaimerLines = doc.splitTextToSize(disclaimerText, 180);
  doc.text(disclaimerLines, 14, 280);

  // Save the PDF
  doc.save('diabetes_risk_report.pdf');
};
